### ISSUE TITLE
 $(...).owlCarousel is not a function Error:

### ISSUE THREAD

**Issue by gwsampso** [mujtaba01/ngx-owl-carousel#1]
Hello,

Using webpack and i get the above error?

In my index.html
```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.0/owl.carousel.min.js"></script>
```

I have imported { OwlModule } from 'ng2-owl-carousel'; in my app.module.ts

Then in my component i have imported { OwlCarousel } from 'ng2-owl-carousel';

and finally my HTML

    <owl-carousel [options]="{items: 3, dots: false, navigation: false}" 
	[items]="images"
	[carouselClasses]="['owl-theme', 'row', 'sliding']">
	<div class="item" class="item" *ngFor=" let m of membersslider ;let i = index">
		<img alt="" [attr.src]='m.teamMemberPhoto' />
	</div>
	</owl-carousel>

Any ideas why its throwing this error

**Comment by mujtaba01** [comment]
You  don't need to include owl carousel 2 in your index.html file. This package already includes the owl.carousel 2.2.0 and this issue is fixed in the latest release.
```bash
#install latest version
npm install --save ng2-owl-carousel@0.1.7
```

If somewhere in your project you have done like this then remove it 

```js
//this line would be causing the issue
import 'imports?jQuery=jquery!owl.carousel';
```

**Comment by gwsampso** [comment]
Thank you this did resolve the issue.

**Comment by gwsampso** [comment]
I've only reopened the issue because i'm unsure how to use the options element?

Much like your next function i tried to apply the same logic to add options 

```
@Input() options: Object;
@ViewChild('owlElement') owlElement: OwlCarousel
```

```
fun() {

  this.owlElement.next([200]);

  this.owlElement.options = {
    loop: true,
    margin: 10,
    responsiveClass: true,
    responsive: {
      0: {
        items: 1,
        nav: true
      },
      600: {
        items: 3,
        nav: false
      },
      1000: {
        items: 7,
        nav: true,
        loop: false
      }
    }
  };
}
```

however nothing changes...

**Comment by mujtaba01** [comment]
After making some change in options you need to call component's refresh method currently Like this:

```typescript

fun() {

  this.owlElement.next([200]);

  this.owlElement.options = {
    loop: true,
    margin: 10,
    responsiveClass: true,
    responsive: {
      0: {
        items: 1,
        nav: true
      },
      600: {
        items: 3,
        nav: false
      },
      1000: {
        items: 7,
        nav: true,
        loop: false
      }
    }
  };

this.owlElement.refresh();
}

```

**Comment by gwsampso** [comment]
confirmed working

thanks

**Comment by evabat** [comment]
I have the same issue, after doing some research I have found that owl carousel tries to get initialized at ngAfterViewInit while the carousel-child is NOT STILL LOADED, please keep in mind that I use my app inside a page with high loading time... The problem occurs mostly when I change roots in my application. Any help would be greatly appreciated.

**Comment by roniewill** [comment]
an't bind to 'options' since it isn't a known property of 'owl-carousel'.
1. If 'owl-carousel' is an Angular component and it has 'options' input, then verify that it is part of this module.
