### ISSUE TITLE
Which name is correct ng2-owl-carousel or angular-owl-carousel?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [mujtaba01/ngx-owl-carousel#12]
On the npm page I see: 
```
npm install ng2-owl-carousel --save
```
But inside github I see: 
```
import { OwlModule } from 'angular-owl-carousel';
```

**Comment by SergeySagan** [comment]
`ng2-owl-carousel` is the only one that works... so... but you're correct the documentation is probably outdated... ie based on angular
