### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'owl-carousel'.

### ISSUE THREAD

**Issue by nadeemse** [mujtaba01/ngx-owl-carousel#13]
Unhandled Promise rejection: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'owl-carousel'.
1. If 'owl-carousel' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'owl-carousel' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("

            <owl-carousel
                [ERROR ->][options]="{items: 3, dots: false, navigation: false}"
                [items]="items"
              "): MostViewedComponent@11:16
Can't bind to 'items' since it isn't a known property of 'owl-carousel'.
1. If 'owl-carousel' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'owl-carousel' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("owl-carousel
                [options]="{items: 3, dots: false, navigation: false}"
                [ERROR ->][items]="items"
                [carouselClasses]="['owl-theme', 'row', 'sliding']">
                "): MostViewedComponent@12:16
Can't bind to 'carouselClasses' since it isn't a known property of 'owl-carousel'.
1. If 'owl-carousel' is an Angular component and it has 'carouselClasses' input, then verify that it is part of this module.
2. If 'owl-carousel' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("tions]="{items: 3, dots: false, navigation: false}"
                [items]="items"
                [ERROR ->][carouselClasses]="['owl-theme', 'row', 'sliding']">
                <div class="item" *ngFor="let it"): MostViewedComponent@13:16
'owl-carousel' is not a known element:
1. If 'owl-carousel' is an Angular component, then verify that it is part of this module.
2. If 'owl-carousel' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
       <div class="col-sm-12">

            [ERROR ->]<owl-carousel
                [options]="{items: 3, dots: false, navigation: false}"
                "): MostViewedComponent@10:12 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError {__zone_symbol__error: Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'owl-carous……} Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'owl-carousel'.
1. If 'owl-carousel' is an Angular component and it has 'options' input, then verify that it is part of this module.
2. If 'owl-carousel' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("

            <owl-carousel
                [ERROR ->][options]="{items: 3, dots: false, navigation: false}"
                [items]="items"
              "): MostViewedComponent@11:16
Can't bind to 'items' since it isn't a known property of 'owl-carousel'.
1. If 'owl-carousel' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'owl-carousel' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("owl-carousel
                [options]="{items: 3, dots: false, navigation: false}"
                [ERROR ->][items]="items"
                [carouselClasses]="['owl-theme', 'row', 'sliding']">
                "): MostViewedComponent@12:16
Can't bind to 'carouselClasses' since it isn't a known property of 'owl-carousel'.
1. If 'owl-carousel' is an Angular component and it has 'carouselClasses' input, then verify that it is part of this module.
2. If 'owl-carousel' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
 ("tions]="{items: 3, dots: false, navigation: false}"
                [items]="items"
                [ERROR ->][carouselClasses]="['owl-theme', 'row', 'sliding']">
                <div class="item" *ngFor="let it"): MostViewedComponent@13:16
'owl-carousel' is not a known element:
1. If 'owl-carousel' is an Angular component, then verify that it is part of this module.
2. If 'owl-carousel' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("
       <div class="col-sm-12">

            [ERROR ->]<owl-carousel
                [options]="{items: 3, dots: false, navigation: false}"
                "): MostViewedComponent@10:12
    at SyntaxError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:1024:33)
    at SyntaxError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:99977:16)
    at new SyntaxError (http://localhost:4200/vendor.bundle.js:11079:16)
    at TemplateParser.parse (http://localhost:4200/vendor.bundle.js:25405:19)
    at JitCompiler._compileTemplate (http://localhost:4200/vendor.bundle.js:61775:68)
    at http://localhost:4200/vendor.bundle.js:61658:62
    at Set.forEach (native)
    at JitCompiler._compileComponents (http://localhost:4200/vendor.bundle.js:61658:19)
    at createResult (http://localhost:4200/vendor.bundle.js:61540:19)
    at ZoneDelegate.webpackJsonp.1227.ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:455:26)
    at Zone.webpackJsonp.1227.Zone.run (http://localhost:4200/polyfills.bundle.js:326:43)
    at http://localhost:4200/polyfills.bundle.js:748:57
    at ZoneDelegate.webpackJsonp.1227.ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:488:35)
    at Zone.webpackJsonp.1227.Zone.runTask (http://localhost:4200/polyfills.bundle.js:364:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.bundle.js:646:35)
consoleError @ zone.js:420
_loop_1 @ zone.js:449
drainMicroTaskQueue @ zone.js:453
zone.js:422 ZoneAwareError {__zone_symbol__error: Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'options' since it isn't a……}

**Comment by lukemcd** [comment]
I have run into this issue as well when trying to use this library.

It would be great if a simple working example were included.

**Comment by sergey-morenets** [comment]
Hi @nadeemse @lukemcd 

Which version of this library are you using? Here are my steps to install:

npm install script-loader --save
npm install angular-owl-carousel --save-dev

After that it worked properly:

```
<owl-carousel
      [options]="galleryCarouselOptions"
      [items]="images">
      <div class="item" *ngFor="let image of images">
        <img [src]="image" />
      </div>
    </owl-carousel>
```

**Comment by CarlosAyala** [comment]
Hi!.
I have the same problem

`
Can't bind to 'options' since it isn't a known property of 'owl-carousel'.
`

**Comment by mujtaba01** [comment]
Hi @CarlosAyala @lukemcd @nadeemse 

I believe if you would have followed the instructions given in the [README](https://github.com/mujtaba01/ng2-owl-carousel/blob/master/README.MD) of this repo exactly. You should not face this issue.

**Comment by CarlosAyala** [comment]
Hi @mujtaba01 .
I have tried some solutions, and now I have another error that I can't fix.
`
ERROR Error: Uncaught (in promise): InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '--' is not a valid attribute name.
Error: Failed to execute 'setAttribute' on 'Element': '--' is not a valid attribute name.
`

This error is thrown when i add the <owl-carousel tag.

**Comment by CarlosAyala** [comment]
Sorry @mujtaba01 . I tried to do this wrapper work, 
I have managed to eliminate the errors, but now the images of the slide  appear all in vertical without the carousel functionality. Css problem maybe?

I gonna try another wrapper or carousel plugin for angular.

Thank you.
