### ISSUE TITLE
Dots:true not working

### ISSUE THREAD

**Issue by jamilalisgandarov** [mujtaba01/ngx-owl-carousel#14]
First of all I want to note that I have included owl.carousel.css file in the index.html and the main problem is that as an option I have included dots:true but it still shows disabled class in the owl-dots div. 

**HTML side**
`<div class="main-carousel">
    <div class="wrapper">
        <owl-carousel [options]="{items: 2,loop:true, margin:20, dots:true}" [carouselClasses]="['owl-
             theme','owl-default', 'row', 'sliding']">
            <div class="item"></div>
            <div class="item">
             
            </div>
        </owl-carousel>
    </div>
</div>`

**Comment by mujtaba01** [comment]
Hi @jamilalisgandarov You may have missed to include owl.carousel/dist/assets/owl.theme.default.css file.
