### ISSUE TITLE
Angular Universal

### ISSUE THREAD

**Issue by thomasnelson4** [mujtaba01/ngx-owl-carousel#15]
Are there any plans to make this library compatible with Angular Universal?

**Comment by ist1373** [comment]
I'm not sure that the functionality of lib not change but i just remove "(window.Zepto || window.jQuery, window, document)" from server.js and put the 
      /^owl.carousel/,
      /^ngx-owl-carousel/,
in whitelist of nodeExternals in webpack.config.js
it's seems to works properly

**Comment by ishankhare07** [comment]
is there any update on this issue?

**Comment by mujtaba01** [comment]
Hi All, Sorry for late response.
Currently this package does not support angular universal however you can eliminate errors and run your app by referring to the latest README. Also you will need to update your package using `npm install --save ngx-owl-carousel@latest`

**Comment by mukesh552** [comment]
[ts] Generic type 'IterableDiffer<V>' requires 1 type argument(s).


import IterableDiffer

y eoor aa ri h iska
