### ISSUE TITLE
app.module.ts (9,27): Cannot find module 'ng2-owl-carousel'.)

### ISSUE THREAD

**Issue by rainstormza** [mujtaba01/ngx-owl-carousel#2]
app.module.ts (9,27): Cannot find module 'ng2-owl-carousel'.)

when I install and import it to appmodule.ts error happened

using angular-cli to create project

**Comment by Rj-s** [comment]
I am also using angular-cli and facing same issue -> "Cannot find module 'ng2-owl-carousel'"

**Comment by mujtaba01** [comment]
```bash
$ npm install ng2-owl-carousel@latest --save #should fix this issue
```
