### ISSUE TITLE
Get the current slide ( src ) and use it outside the scope

### ISSUE THREAD

**Issue by lexcaraig** [mujtaba01/ngx-owl-carousel#20]
Hi, i would like to ask if something like this is possible? I am currently working on this. Any help? I really appreciate it.

```
<div>
    // i would actually like to put the image.preview here
</div>

<ng2-owl-carousel2
     [options]="carouselOptions">
            <div class="owl-item" *ngFor="let image of carousel; let i = index">
                <img [src]="image.cover" alt="image.title">
                 // it has image.preview
            </div>
 </ng2-owl-carousel2>
```

Thanks,
Best Regards, Lex

**Comment by lexcaraig** [comment]
Hi @mujtaba01 i hope this finds you well. :) Thanks!

**Comment by mujtaba01** [comment]
Hi @lexcaraig this is not possible as of now.

**Comment by mujtaba01** [comment]
Closing this issue as you are using different plugin. 

However this can be done by using onChanged callback in options input and the selected item index can be found by accessing event.item.index.
