### ISSUE TITLE
Give navText to slider

### ISSUE THREAD

**Issue by shabbir-dhangot** [mujtaba01/ngx-owl-carousel#22]
I have seen couple of example to give arrow icons to slider. But I am unable to do it.

Below is my Implementation. 

    <owl-carousel #owlSlider
            [options]="{nav : false, dots: false, loop:false, items:1, navText:['<i class='fa fa-chevron-circle-left' aria-hidden='true'></i>','<i class='fa fa-chevron-circle-right' aria-hidden='true'></i>']}"
            [items]="images"
            [carouselClasses]="['owl-theme', 'sliding']">
        <div class="item deal-slide" *ngFor="let image of images;let i = index">
          
          <div class="coupons-div" style="cursor:pointer;">
            <img class="deals-image" src="http://lorempixel.com/1080/300/{{image}}"/><br/>
          </div>
        </div>
      </owl-carousel>

below is error showing on the console.

<pre>
Uncaught Error: Template parse errors:
Parser Error: Missing expected ] at column 69 in [{nav : false, dots: false, loop:false, items:1, navText:['<i class='fa fa-chevron-circle-left' aria-hidden='true'></i>','<i class='fa fa-chevron-circle-right' aria-hidden='true'></i>']}] </pre>

for some reason complete error not showing by github. PFA of screenshot.
![screenshot from 2017-07-24 18-43-26](https://user-images.githubusercontent.com/8267282/28524914-0e33c8ec-70a0-11e7-81a0-bd7dafb2e967.png)

**Comment by mujtaba01** [comment]
Set the options key in your components ts file and it will work

**Comment by shabbir-dhangot** [comment]
Can you provide sample respective to this? Unable to find any implementation on readme file.

**Comment by mujtaba01** [comment]
Do something like this in your ts file:
```ts
carouselOptions: any = {
    nav : false, 
    dots: false, 
    loop:false, 
    items:1, 
    navText:['<i class='fa fa-chevron-circle-left' aria-hidden='true'></i>','<i class='fa fa-chevron-circle-right' aria-hidden='true'></i>']
}
```

and in html

```html
<owl-carousel #owlSlider
        [options]="carouselOptions"
        [items]="images"
        [carouselClasses]="['owl-theme', 'sliding']">
    <div class="item deal-slide" *ngFor="let image of images;let i = index">
      
      <div class="coupons-div" style="cursor:pointer;">
        <img class="deals-image" src="http://lorempixel.com/1080/300/{{image}}"/><br/>
      </div>
    </div>
  </owl-carousel>
```

**Comment by shabbir-dhangot** [comment]
Also buttons coming down the carousel not left and right.

**Comment by shabbir-dhangot** [comment]
Adding modified options
    carouselOptions: any = {
      nav : true, 
      dots: false, 
      loop:false, 
      items:1, 
      navText:['<i class="fa fa-chevron-circle-left" aria-hidden="true"></i>','<i class="fa fa-chevron-circle-right" aria-hidden="true"></i>']
     }

**Comment by Shofol** [comment]
I think The Navtext should be defined with template literales (`) not with ( ' ) - 
```javascript
 navText: [ `<i class='fa fa-chevron-circle-left' aria-hidden='true'></i>`, `<i class='fa fa-chevron-circle-right' aria-hidden='true'></i>`]
```
It is working for me.
