### ISSUE TITLE
callback function not working properly

### ISSUE THREAD

**Issue by shabbir-dhangot** [mujtaba01/ngx-owl-carousel#23]
carouselOptions: any = {
      nav : true, 
      dots: false, 
      loop:false,
      onChange : this.onChange, 
      items:1, 
      navText:['<i class="fa fa-chevron-circle-left" aria-hidden="true"></i>','<i class="fa fa-chevron-circle-right" aria-hidden="true"></i>']
      }

I have written callback function for onChange event. Its printing console correctly. But when I want to access other function or variable it always showing as undefined. 

For example I want to access owlSlider1 then it showing undefined in that method only. on other methods that variable is working

**Comment by mujtaba01** [comment]
Change this.onChange to this.onChange.bind(this)

**Comment by shabbir-dhangot** [comment]
This basic event binding information need to be in readme file.
