### ISSUE TITLE
Blink effect

### ISSUE THREAD

**Issue by VladislavSamoylenko** [mujtaba01/ngx-owl-carousel#24]
Blink effect when new item is added in ngFor array. 
It is look like that all items in carousel are reloads and then appears

**Comment by mujtaba01** [comment]
Yes there is blink effect. This is because on adding items to the array the owl.carousel needs to be reinitialized.

**Comment by shtaif** [comment]
Yeah, it appears that not only they "blink" as mentioned, but also the carousel is being reset back to the first slide.
So even if not considering any Angular here, Owl carousel itself must be initialized anytime a slide is added thus blinking and losing the current active slide index?

**Comment by TheCodonist** [comment]
so can we add transition when the carousel is reinitialized????

**Comment by mauricenaef** [comment]
+1 For the transition.. has anybody figured it out so far? Thanks
