### ISSUE TITLE
owl.carousel.js:1658 Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by rainstormza** [mujtaba01/ngx-owl-carousel#3]
owl.carousel.js:1658 Uncaught TypeError: Cannot read property 'fn' of undefined
    at owl.carousel.js:1658
    at Object.<anonymous> (owl.carousel.js:1695)
    at __webpack_require__ (bootstrap 2c4170b…:52)
    at Object.Owl.Defaults.items (index.js:18)
    at __webpack_require__ (bootstrap 2c4170b…:52)
    at Object.433 (main.ts:11)
    at __webpack_require__ (bootstrap 2c4170b…:52)
    at Object.434 (app.component.ts:17)
    at __webpack_require__ (bootstrap 2c4170b…:52)
    at Object.324 (src async:7)
    at __webpack_require__ (bootstrap 2c4170b…:52)
    at Object.553 (main.bundle.js:181)
    at __webpack_require__ (bootstrap 2c4170b…:52)
    at webpackJsonpCallback (bootstrap 2c4170b…:23)
    at main.bundle.js:1
(anonymous) @ owl.carousel.js:1658
(anonymous) @ owl.carousel.js:1695
__webpack_require__ @ bootstrap 2c4170b…:52
Owl.Defaults.items @ index.js:18
__webpack_require__ @ bootstrap 2c4170b…:52
433 @ main.ts:11
__webpack_require__ @ bootstrap 2c4170b…:52
434 @ app.component.ts:17
__webpack_require__ @ bootstrap 2c4170b…:52
324 @ src async:7
__webpack_require__ @ bootstrap 2c4170b…:52
553 @ main.bundle.js:181
__webpack_require__ @ bootstrap 2c4170b…:52
webpackJsonpCallback @ bootstrap 2c4170b…:23
(anonymous) @ main.bundle.js:1

lastest version still error like this

Edit : import jquery

**Comment by rainstormza** [comment]
![2wkpl2n](https://cloud.githubusercontent.com/assets/4003032/23388451/dd9b2f0a-fd94-11e6-930e-8c54a583a869.png)

but there is no carousel

my code 

html

 <owl-carousel [options]="{items: 3, dots: false, navigation: false}" [items]="images" [carouselClasses]="['owl-theme', 'row', 'sliding']">
     <div class="item" *ngFor="let image of images;let i = index">
         <div class="thumbnail-image" [ngStyle]=""><img src="#" alt=""></div>
     </div>
 </owl-carousel>


typescript

import { Component, ViewChild } from '@angular/core';
import {OwlCarousel} from 'ng2-owl-carousel';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app works!';
  @ViewChild('owlElement') owlElement: OwlCarousel

  images: Array<any>  = [0,1,2,3,4,5,6,7,8,9,10];

  fun() {
     this.owlElement.next([200])
     //duration 200ms
   }
}

**Comment by mujtaba01** [comment]
Update scripts key in your angular-cli.json to include jQuery

"scripts": [
  "../node_modules/jquery/dist/jquery.js"
]

[http://ayoubgdah.com/blog/using-jquery-with-angular-2-angular-cli/](url)

**Comment by rainstormza** [comment]
![1488276937209](https://cloud.githubusercontent.com/assets/4003032/23401252/98b975c8-fdd9-11e6-9498-0c5bdc85a310.gif)

error was gone but data doesn't look like what I expect 
Is this about owl carousel css file ?

**Comment by mujtaba01** [comment]
Yes you need to include owl carousel css file.

**Comment by amitgaur208** [comment]
This issue not solved for me..
