### ISSUE TITLE
Possibility to reInit owlCarousel

### ISSUE THREAD

**Issue by sayhicoelho** [mujtaba01/ngx-owl-carousel#33]
When using the `refresh()` method the view makes some annoying things like the following GIF I've made for this issue: 

![fucking gif](https://user-images.githubusercontent.com/8188365/33516825-5615c31e-d760-11e7-8bc1-9f592f6525db.gif)

This happens because we've a `refresh()` method that turn off the view and then turn it on using `*ngIf`.

**Comment by mujtaba01** [comment]
install latest version  `npm install --save ngx-owl-carousel@latest`
