### ISSUE TITLE
Angular 4.0 - ERROR TypeError: this._trackByFn is not a function

### ISSUE THREAD

**Issue by netopolit** [mujtaba01/ngx-owl-carousel#5]
With Angular 4.0 plugin fails with error ERROR TypeError: this._trackByFn is not a function.

Thank you :)

**Comment by thomasnelson4** [comment]
I came here to say the same thing... wish that I could give more info, but there isn't much more to give..

**Comment by Rj-s** [comment]
Facing same issue. I would appreciate help.

**Comment by mujtaba01** [comment]
I will update the package soon to support angular 4

**Comment by mujtaba01** [comment]
Latest version should fix the issue.
```bash
npm install --save ng2-owl-carousel@latest
```

**Comment by mujtaba01** [comment]
Latest version should fix the issue.
```bash
npm install --save ng2-owl-carousel@latest
```
