### ISSUE TITLE
Listening Owl Carousel 2 Events

### ISSUE THREAD

**Issue by labibramadhan** [mujtaba01/ngx-owl-carousel#6]
How to listen to [Owl Carousel 2 Events](https://owlcarousel2.github.io/OwlCarousel2/docs/api-events.html)?

I have tried something like this:
```js
ngAfterViewInit() {
  const owl = $(this._elementRef.nativeElement).find('owl-carousel-child').data('owl.carousel');
  owl.on('onResize, onResized, onInitialize, onInitialized, onChange, onChanged, onDrag', console.log);
}
```

But nothing triggered

**Comment by mujtaba01** [comment]
Instead of listening to Owl Carousel events you can pass the callback in options input.

**Comment by aalvarez255** [comment]
@mujtaba01 Could you provide an example, please?

I tried to catch the "changed" event with no luck:

```
owlOptions = {
  changed: callbackFunction
}
```

Thank you.

**Comment by labibramadhan** [comment]
Thank you! it works.
