### ISSUE TITLE
Move nav divs out of component 

### ISSUE THREAD

**Issue by abelkbil** [mujtaba01/ngx-owl-carousel#8]
How can I move previous and next div out of component section.
Please enable wiki, so that we can update these answers there.
Thanks.

**Comment by mujtaba01** [comment]
To hide default previous and next buttons you need to pass {navigation: false} in options input. Create next and previous buttons manually outside the component and call component's previous and next function on click events.
Like this:
```html

<button (click)="owl.previous()">Previous</button>

<owl-carousel [items]="images" #owl [options]="{ navigation: false}" [carouselClasses]="carouselClasses">
    <div *ngFor="let image of images">
        <div [ngStyle]="{'background-image': 'url(' + image.url  + ')'}"></div>
    </div>
</owl-carousel>

<button (click)="owl.next()">Next</button>
```

**Comment by abelkbil** [comment]
@mujtaba01  Thanks a lot.
